name: Deploy to AWS Amplify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Pull Amplify environment
        run: |
          amplify pull \
            --appId ${{ secrets.AMPLIFY_APP_ID }} \
            --envName production \
            --yes

      - name: Build application
        run: npm run build

      - name: Deploy to Amplify
        run: amplify publish --yes
        env:
          AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}

      - name: Notify deployment status
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'ContextChef deployment to production ${{ job.status }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}